<?php
$this->pageCaption='Ver '.Informe::classNameLabel().' #'.$model->id;
$this->pageTitle=Yii::app()->name . ' - ' . $this->pageCaption;
$this->pageDescription='';
$this->breadcrumbs=array(
	Informe::classNameLabel()=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'Listar '.Informe::classNameLabel(), 'url'=>array('index')),
	array('label'=>'Crear '. Informe::classNameLabel(), 'url'=>array('create')),
	array('label'=>'Actualizar '. Informe::classNameLabel(), 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Eliminar '. Informe::classNameLabel(), 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'¿Estas seguro que quieres eliminar este elemento?')),
	array('label'=>'Administrar '.Informe::classNameLabel(), 'url'=>array('admin')),
);
?>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'baseScriptUrl'=>false,
	'cssFile'=>false,
	'htmlOptions'=>array('class'=>'table table-bordered table-striped'),
	'attributes'=>array(
		'id',
		'numeroPersonasNomina',
		'numeroPersonasAsimilables',
		'numeroPersonasProfesionales',
		'numeroPersonasVoluntarias',
		'numeroPersonasPrestadoresSS',
		'numeroPersonasTotales',
		'numeroBeneficiariosTotales',
		'numeroBeneficiariosNinosH',
		'numeroBeneficiariosNinosM',
		'numeroBeneficiariosJovenesH',
		'numeroBeneficiariosJovenesM',
		'numeroBeneficiariosAdultosH',
		'numeroBeneficiariosAdultosM',
		'numeroBeneficiariosMayorH',
		'numeroBeneficiariosMayorM',
		'numeroBeneficiariosIndirectos',
		'nombreProgramaUno',
		'nombreProgramaDos',
		'nombreProgramaTres',
		'nombreProgramaCuatro',
		'nombreProgramaCinco',
		'horasVoluntariosProgramaUno',
		'horasVoluntariosProgramaDos',
		'horasVoluntariosProgramaTres',
		'horasVoluntariosProgramaCuatro',
		'horasVoluntariosProgramaCinco',
		'nombreConvocatoriaUno',
		'nombreConvocatoriaDos',
		'nombreConvocatoriaTres',
		'nombreConvocatoriaCuatro',
		'nombreConvocatoriaCinco',
		'nombreConvocatoriaSeis',
		'nombreConvocatoriaSiete',
		'nombreConvocatoriaOcho',
		'nombreConvocatoriaNueve',
		'nombreConvocatoriaDiez',
		'aprovadaConvocatoriaUno',
		'aprovadaConvocatoriaDos',
		'aprovadaConvocatoriaTres',
		'aprovadaConvocatoriaCuatro',
		'aprovadaConvocatoriaCinco',
		'aprovadaConvocatoriaSeis',
		'aprovadaConvocatoriaSiete',
		'aprovadaConvocatoriaOcho',
		'aprovadaConvocatoriaNueve',
		'aprovadaConvocatoriaDiez',
		'periodico',
		'radio',
		'espectaculares',
		'informeImpreso',
		'revistas',
		'television',
		'folletos',
		'redesSociales',
		'paginaWeb',
		'otros',
		'ninguna',
		array(	'name'=>'institucion_aid',
		        'value'=>$model->institucion->nombre,),
		array(	'name'=>'ejercicioFiscal_did',
		        'value'=>$model->ejercicioFiscal->nombre,),
		array(	'name'=>'estatus_did',
		        'value'=>$model->estatus->nombre,),
		'editable',
		'ultimaModificacion_dt',
	),
)); ?>
